const Business = require('../models/business');

const PLAN_LIMITS = {
  free: { websites: 1, bookingsPerMonth: 10 },
  starter: { websites: 5, bookingsPerMonth: 100 },
  pro: { websites: Infinity, bookingsPerMonth: Infinity }
};

const checkWebsiteLimit = async (req, res, next) => {
  try {
    const userPlan = req.user.subscription?.plan || 'free';
    const limits = PLAN_LIMITS[userPlan];

    // Count websites already generated by this owner
    const count = await Business.countDocuments({ ownerId: req.user._id });

    if (count >= limits.websites) {
      return res.status(403).json({
        success: false,
        message: `Subscription limit reached. Your current plan (${userPlan.toUpperCase()}) allows a maximum of ${limits.websites} website(s). Please upgrade to create more sites.`,
        limitReached: true
      });
    }

    next();
  } catch (error) {
    console.error(error);
    res.status(500).json({ success: false, message: 'Server error checking subscription limits' });
  }
};

module.exports = { checkWebsiteLimit, PLAN_LIMITS };
